//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionaireLocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annonce
    {
        public Annonce()
        {
            this.Demandes = new HashSet<Demande>();
        }
    
        public int IDAnnonce { get; set; }
        public int IDBailleur { get; set; }
        public int IDAppartement { get; set; }
        public System.DateTime DatePub { get; set; }
        public double Prix { get; set; }
        public string Motif { get; set; }
        public int NbMaxCol { get; set; }
        public int Visibilite { get; set; }
    
        public virtual Appartement Appartement { get; set; }
        public virtual Bailleur Bailleur { get; set; }
        public virtual ICollection<Demande> Demandes { get; set; }
    }
}
