//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionaireLocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bailleur
    {
        public Bailleur()
        {
            this.Annonces = new HashSet<Annonce>();
        }
    
        public int IDBailleur { get; set; }
        public string Telephone { get; set; }
        public string Adresse { get; set; }
        public string InfoSupp { get; set; }
    
        public virtual ICollection<Annonce> Annonces { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
