//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Annonce
{
    public Annonce()
    {
        this.Demandes = new HashSet<Demande>();
    }

    public int IDAnnonce { get; set; }
    public int IDBailleur { get; set; }
    public int IDAppartement { get; set; }
    public System.DateTime DatePub { get; set; }
    public double Prix { get; set; }
    public string Motif { get; set; }
    public int NbMaxCol { get; set; }
    public int Visibilite { get; set; }

    public virtual Appartement Appartement { get; set; }
    public virtual Bailleur Bailleur { get; set; }
    public virtual ICollection<Demande> Demandes { get; set; }
}

public partial class Appartement
{
    public Appartement()
    {
        this.Annonces = new HashSet<Annonce>();
    }

    public int IDAppartement { get; set; }
    public double Superficie { get; set; }
    public int NbPieces { get; set; }
    public int Parking { get; set; }
    public int NbEtage { get; set; }
    public string Type { get; set; }
    public string Lieu { get; set; }
    public string InfoSupp { get; set; }

    public virtual ICollection<Annonce> Annonces { get; set; }
}

public partial class Bailleur
{
    public Bailleur()
    {
        this.Annonces = new HashSet<Annonce>();
    }

    public int IDBailleur { get; set; }
    public string Telephone { get; set; }
    public string Adresse { get; set; }
    public string InfoSupp { get; set; }

    public virtual ICollection<Annonce> Annonces { get; set; }
    public virtual Utilisateur Utilisateur { get; set; }
}

public partial class Demande
{
    public int IDLocataire { get; set; }
    public int IDAnnonce { get; set; }
    public System.DateTime DateDemande { get; set; }
    public int Status { get; set; }
    public string Commentaire { get; set; }

    public virtual Annonce Annonce { get; set; }
    public virtual Locataire Locataire { get; set; }
}

public partial class Locataire
{
    public Locataire()
    {
        this.Demandes = new HashSet<Demande>();
    }

    public int IDLocataire { get; set; }
    public string Telephone { get; set; }
    public string Addresse { get; set; }
    public string Civilite { get; set; }
    public Nullable<System.DateTime> DateNaiss { get; set; }
    public string Profession { get; set; }
    public string EtatCivil { get; set; }
    public Nullable<int> Fumeur { get; set; }
    public string InfoSupp { get; set; }

    public virtual ICollection<Demande> Demandes { get; set; }
    public virtual Utilisateur Utilisateur { get; set; }
}

public partial class Utilisateur
{
    public int IDUser { get; set; }
    public string nom { get; set; }
    public string login { get; set; }
    public string motdepasse { get; set; }
    public int seed { get; set; }
    public string type { get; set; }

    public virtual Bailleur Bailleur { get; set; }
    public virtual Locataire Locataire { get; set; }
}
