//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionaireLocation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GesLocEntities : DbContext
    {
        public GesLocEntities()
            : base("name=GesLocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Annonce> Annonces { get; set; }
        public DbSet<Appartement> Appartements { get; set; }
        public DbSet<Bailleur> Bailleurs { get; set; }
        public DbSet<Demande> Demandes { get; set; }
        public DbSet<Locataire> Locataires { get; set; }
        public DbSet<Utilisateur> Utilisateurs { get; set; }
        public DbSet<Ville> Villes { get; set; }
    }
}
