//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionaireLocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int IDUser { get; set; }
        public string nom { get; set; }
        public string login { get; set; }
        public string motdepasse { get; set; }
    
        public virtual Bailleur Bailleur { get; set; }
        public virtual Locataire Locataire { get; set; }
    }
}
